FROM maven:alpine

VOLUME root/.m2
VOLUME root/.PaymentService

# Create app directory

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY PaymentService/pom.xml /usr/src/app

RUN mvn verify clean --fail-never

# Adding source, compile and package into a fat jar
COPY PaymentService/src /usr/src/app/src

RUN mvn verify

EXPOSE 8080

CMD mvn jetty:run